// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fojtrnvtlktxxjffcsqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvanRybnZ0bGt0eHhqZmZjc3FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMDg4MzcsImV4cCI6MjA2OTU4NDgzN30.IZvyt_8koJSt_zeUBadsVjHF1fSFQmNNKPbQUNcIkmc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});